version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  build:
    commands:
      - dotnet restore
      - dotnet build -c Release
      - dotnet publish -c Release -o ./publish
  post_build:
    commands:
      - aws lambda update-function-code --function-name MyFirstLambda --zip-file fileb://./publish/MyFirstLambda.zip