version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet build --configuration Release
      - dotnet publish -c Release -o ./publish -r linux-x64
  post_build:
    commands:
      - echo Packaging artifact
      - cd ./publish
      - zip -r MyFirstLambda.zip .
      - aws s3 cp MyFirstLambda.zip s3://your-lambda-artifacts-bucket/MyFirstLambda.zip
artifacts:
  files:
    - MyFirstLambda.zip
